name: Publish to NPM

on:
  push:
    tags:
      - 'v*' # 推送版本标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION"
          
      - name: Verify version format
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format: $VERSION"
            echo "Version must be in format: v1.0.0"
            exit 1
          fi
          echo "✅ Version format valid: $VERSION"
          
      - name: Check version consistency
        run: |
          TAG_VERSION="${{ steps.version.outputs.version }}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          
          # Remove 'v' prefix for comparison
          TAG_VERSION_CLEAN=${TAG_VERSION#v}
          
          if [[ "$TAG_VERSION_CLEAN" != "$PKG_VERSION" ]]; then
            echo "❌ Version mismatch!"
            echo "Tag version: $TAG_VERSION_CLEAN"
            echo "Package.json version: $PKG_VERSION"
            echo "Please ensure tag version matches package.json version"
            exit 1
          fi
          echo "✅ Version consistency verified: $TAG_VERSION_CLEAN"
          
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
